// One numbered step in an orchestra card (ui-spec §4.4): the step's digit in a ring badge, then
// its label, which wraps. Below `sm` the badge sits on the card's top-left edge (masked by
// `bg-band`; the card is its positioning box), so the label takes the card's full width; from `sm`
// it sits inline before the label. The digit is the step's place in the flow, generated by the
// caller, never a content slot. ⑤, the fix, is in the accent.
type OrchestraStepProps = {
  readonly step: number;
  readonly label: string;
  /** ⑤, the fix: badge and label in the accent. */
  readonly accent?: boolean;
};

const badge =
  "absolute -top-2.5 left-1.5 grid size-5 shrink-0 place-items-center rounded-full border bg-band font-mono text-meta leading-none sm:static";
const text = "min-w-0 font-mono text-meta leading-4 wrap-break-word sm:pt-0.5";

export function OrchestraStep({ step, label, accent = false }: OrchestraStepProps) {
  return (
    <div data-anim="orch-step" data-step={step} className="flex items-start gap-1.5">
      <span className={`${badge} ${accent ? "border-accent text-accent" : "border-muted text-text"}`}>
        {step}
      </span>
      <span className={`${text} ${accent ? "text-accent" : "text-text"}`}>{label}</span>
    </div>
  );
}
